#!/usr/bin/env python

try:
    # Change the process name.
    import ctypes
    libc = ctypes.CDLL('libc.so.6')
    libc.prctl(15, 'OkeykoClient', 0, 0)
except:
    pass

import okeyko

okeyko.main()